name: Import Issues from CSV

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Import Issues
        run: |
          tail -n +2 issues.csv | while IFS=',' read -r Title Description Phase Layer Priority
          do
            echo "Creating issue: $Title"

            gh issue create \
              --title "$Title" \
              --body "$Description" \
              --label "$Layer" \
              || echo "Failed for $Title"

          done
